apiVersion: apps/v1
kind: Deployment

metadata:
  name: hackatonfiap-donations
  namespace: fcg
  labels:
    app: hackatonfiap-donations

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hackatonfiap-donations

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: hackatonfiap-donations
        azure.workload.identity/use: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"

    spec:
      serviceAccountName: sa-fcg-catalog

      imagePullSecrets:
        - name: acr-secret

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: hackatonfiap-donations-secrets

      containers:
        - name: hackatonfiap-donations

          image: fcgregistry.azurecr.io/hackatonfiap-donations:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-donations-secret
                  key: ConnectionStrings__Default

            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-donations-secret
                  key: ServiceBus__ConnectionString

            - name: Cosmos__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-donations-secret
                  key: Cosmos__ConnectionString

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: hackatonfiap-donations-secret
                  key: Jwt__Key

          resources:
            requests:
              cpu: 50m
              memory: 96Mi

            limits:
              cpu: 500m
              memory: 384Mi

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
