apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hackatonfiap-donations-secrets
  namespace: fcg
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 8ec28240-b8eb-45b2-847d-b477002860f3
    tenantId: 6c5cda55-11ba-4255-a1b6-f408421a47be
    keyvaultName: kv-fcg-prod

    objects: |
      array:
        - |
          objectName: Donations-ConnectionString
          objectType: secret
        - |
          objectName: ServiceBus-ConnectionString
          objectType: secret
        - |
          objectName: Cosmos-ConnectionString
          objectType: secret
        - |
          objectName: Jwt-Key
          objectType: secret

  secretObjects:
    - secretName: hackatonfiap-donations-secret
      type: Opaque
      data:
        - objectName: Donations-ConnectionString
          key: ConnectionStrings__Default

        - objectName: ServiceBus-ConnectionString
          key: ServiceBus__ConnectionString

        - objectName: Cosmos-ConnectionString
          key: Cosmos__ConnectionString

        - objectName: Jwt-Key
          key: Jwt__Key
